version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
    - db

  blog:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db